
#user nobody;
worker_processes 1;   # Строка 3: Количество воркер-процессов NGINX (установлено 1)

#error_log logs/error.log;
#error_log logs/error.log notice;
#error_log logs/error.log info;

pid /home/runner/workspace/logs/nginx.pid;   # Строка 9: Путь к файлу с PID главного процесса


events {   # Строка 12: Начало блока events - настройка обработки соединений
    worker_connections 1024;
}   # Строка 14: Закрывающая скобка блока events


http {   # Строка 17: Начало блока http - основная секция конфигурации веб-сервера
    include mime.types;   # Строка 18: Подключает файл mime.types с MIME-типами
    default_type application/octet-stream;   # Строка 19: MIME-тип по умолчанию (двоичный поток)

    #log_format main '$remote_addr - $remote_user [$time_local] "$request"
    #                 '$status $body_bytes_sent "$http_referer"


    access_log /home/runner/workspace/logs/access.log;

    sendfile on;
    #tcp_nopush on;

    #keepalive_timeout 0;
    keepalive_timeout 65;

    #gzip on;

    server {   # Строка 35: Начало блока server - конфигурация виртуального сервера
        listen 8080;   # Строка 36: Прослушивание порта 8080
        server_name localhost;   # Строка 37: Имя виртуального сервера (localhost)

        #charset koi8-r;

        #access_log logs/host.access.log main;

        location / {   # Строка 43: Блок location для обработки корневого пути
            proxy_pass http://127.0.0.1:8181;   # Строка 44: Проксирование запросов на 127.0.0.1:8181


        #error_page 404 /404.html;

        #redirect server error pages to the static page /50x.html

        error_page 500 502 503 504 /50x.html;   # Строка 51: Страница для ошибок 500,502,503,504
        location = /50x.html {   # Строка 52: Блок location для точного совпадения /50x.html
            root html;   # Строка 53: Корневая директория для поиска файла


        }
    }
}
